version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1-bionic
    restart: always
    ports:
      - '27017:27017'
    networks:
      - backend
  app:
    container_name: ts-node-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - CLIENT_URL=${CLIENT_URL}
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge
